// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package projectdetect

import (
	"reflect"
	"testing"
)

func TestAX7_DetectProjectType_Good(t *testing.T) {
	symbol := reflect.ValueOf(DetectProjectType)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected DetectProjectType to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_DetectProjectType_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(DetectProjectType)
	if symbolType == nil {
		t.Fatal("expected DetectProjectType to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected DetectProjectType function type to be printable")
	}
}

func TestAX7_DetectProjectType_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DetectProjectType panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(DetectProjectType)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DetectProjectType to have a callable entry point")
	}
}
