// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package testassert

import (
	"reflect"
	"testing"
)

func TestAX7_Contains_Good(t *testing.T) {
	symbol := reflect.ValueOf(Contains)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Contains to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Contains_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Contains)
	if symbolType == nil {
		t.Fatal("expected Contains to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Contains function type to be printable")
	}
}

func TestAX7_Contains_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Contains panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Contains)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Contains to have a callable entry point")
	}
}

func TestAX7_ElementsMatch_Good(t *testing.T) {
	symbol := reflect.ValueOf(ElementsMatch)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ElementsMatch to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ElementsMatch_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ElementsMatch)
	if symbolType == nil {
		t.Fatal("expected ElementsMatch to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ElementsMatch function type to be printable")
	}
}

func TestAX7_ElementsMatch_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ElementsMatch panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ElementsMatch)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ElementsMatch to have a callable entry point")
	}
}

func TestAX7_Empty_Good(t *testing.T) {
	symbol := reflect.ValueOf(Empty)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Empty to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Empty_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Empty)
	if symbolType == nil {
		t.Fatal("expected Empty to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Empty function type to be printable")
	}
}

func TestAX7_Empty_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Empty panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Empty)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Empty to have a callable entry point")
	}
}

func TestAX7_Equal_Good(t *testing.T) {
	symbol := reflect.ValueOf(Equal)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Equal to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Equal_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Equal)
	if symbolType == nil {
		t.Fatal("expected Equal to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Equal function type to be printable")
	}
}

func TestAX7_Equal_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Equal panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Equal)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Equal to have a callable entry point")
	}
}

func TestAX7_Nil_Good(t *testing.T) {
	symbol := reflect.ValueOf(Nil)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Nil to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Nil_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Nil)
	if symbolType == nil {
		t.Fatal("expected Nil to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Nil function type to be printable")
	}
}

func TestAX7_Nil_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Nil panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Nil)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Nil to have a callable entry point")
	}
}

func TestAX7_Zero_Good(t *testing.T) {
	symbol := reflect.ValueOf(Zero)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Zero to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Zero_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Zero)
	if symbolType == nil {
		t.Fatal("expected Zero to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Zero function type to be printable")
	}
}

func TestAX7_Zero_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Zero panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Zero)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Zero to have a callable entry point")
	}
}
