// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package api

import (
	"reflect"
	"testing"
)

func TestAX7_BuildProvider_BasePath_Good(t *testing.T) {
	symbol := reflect.ValueOf((*BuildProvider).BasePath)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected BuildProvider_BasePath to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_BuildProvider_BasePath_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*BuildProvider).BasePath)
	if symbolType == nil {
		t.Fatal("expected BuildProvider_BasePath to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected BuildProvider_BasePath function type to be printable")
	}
}

func TestAX7_BuildProvider_BasePath_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing BuildProvider_BasePath panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*BuildProvider).BasePath)
	if symbol.Pointer() == 0 {
		t.Fatal("expected BuildProvider_BasePath to have a callable entry point")
	}
}

func TestAX7_BuildProvider_Channels_Good(t *testing.T) {
	symbol := reflect.ValueOf((*BuildProvider).Channels)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected BuildProvider_Channels to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_BuildProvider_Channels_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*BuildProvider).Channels)
	if symbolType == nil {
		t.Fatal("expected BuildProvider_Channels to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected BuildProvider_Channels function type to be printable")
	}
}

func TestAX7_BuildProvider_Channels_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing BuildProvider_Channels panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*BuildProvider).Channels)
	if symbol.Pointer() == 0 {
		t.Fatal("expected BuildProvider_Channels to have a callable entry point")
	}
}

func TestAX7_BuildProvider_Describe_Good(t *testing.T) {
	symbol := reflect.ValueOf((*BuildProvider).Describe)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected BuildProvider_Describe to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_BuildProvider_Describe_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*BuildProvider).Describe)
	if symbolType == nil {
		t.Fatal("expected BuildProvider_Describe to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected BuildProvider_Describe function type to be printable")
	}
}

func TestAX7_BuildProvider_Describe_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing BuildProvider_Describe panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*BuildProvider).Describe)
	if symbol.Pointer() == 0 {
		t.Fatal("expected BuildProvider_Describe to have a callable entry point")
	}
}

func TestAX7_BuildProvider_Element_Good(t *testing.T) {
	symbol := reflect.ValueOf((*BuildProvider).Element)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected BuildProvider_Element to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_BuildProvider_Element_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*BuildProvider).Element)
	if symbolType == nil {
		t.Fatal("expected BuildProvider_Element to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected BuildProvider_Element function type to be printable")
	}
}

func TestAX7_BuildProvider_Element_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing BuildProvider_Element panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*BuildProvider).Element)
	if symbol.Pointer() == 0 {
		t.Fatal("expected BuildProvider_Element to have a callable entry point")
	}
}

func TestAX7_BuildProvider_Name_Good(t *testing.T) {
	symbol := reflect.ValueOf((*BuildProvider).Name)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected BuildProvider_Name to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_BuildProvider_Name_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*BuildProvider).Name)
	if symbolType == nil {
		t.Fatal("expected BuildProvider_Name to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected BuildProvider_Name function type to be printable")
	}
}

func TestAX7_BuildProvider_Name_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing BuildProvider_Name panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*BuildProvider).Name)
	if symbol.Pointer() == 0 {
		t.Fatal("expected BuildProvider_Name to have a callable entry point")
	}
}

func TestAX7_BuildProvider_RegisterRoutes_Good(t *testing.T) {
	symbol := reflect.ValueOf((*BuildProvider).RegisterRoutes)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected BuildProvider_RegisterRoutes to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_BuildProvider_RegisterRoutes_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*BuildProvider).RegisterRoutes)
	if symbolType == nil {
		t.Fatal("expected BuildProvider_RegisterRoutes to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected BuildProvider_RegisterRoutes function type to be printable")
	}
}

func TestAX7_BuildProvider_RegisterRoutes_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing BuildProvider_RegisterRoutes panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*BuildProvider).RegisterRoutes)
	if symbol.Pointer() == 0 {
		t.Fatal("expected BuildProvider_RegisterRoutes to have a callable entry point")
	}
}

func TestAX7_NewProvider_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewProvider)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewProvider to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewProvider_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewProvider)
	if symbolType == nil {
		t.Fatal("expected NewProvider to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewProvider function type to be printable")
	}
}

func TestAX7_NewProvider_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewProvider panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewProvider)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewProvider to have a callable entry point")
	}
}
