// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package generators

import (
	"reflect"
	"testing"
)

func TestAX7_GoGenerator_Available_Good(t *testing.T) {
	symbol := reflect.ValueOf((*GoGenerator).Available)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected GoGenerator_Available to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_GoGenerator_Available_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*GoGenerator).Available)
	if symbolType == nil {
		t.Fatal("expected GoGenerator_Available to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected GoGenerator_Available function type to be printable")
	}
}

func TestAX7_GoGenerator_Available_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing GoGenerator_Available panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*GoGenerator).Available)
	if symbol.Pointer() == 0 {
		t.Fatal("expected GoGenerator_Available to have a callable entry point")
	}
}

func TestAX7_GoGenerator_Generate_Good(t *testing.T) {
	symbol := reflect.ValueOf((*GoGenerator).Generate)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected GoGenerator_Generate to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_GoGenerator_Generate_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*GoGenerator).Generate)
	if symbolType == nil {
		t.Fatal("expected GoGenerator_Generate to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected GoGenerator_Generate function type to be printable")
	}
}

func TestAX7_GoGenerator_Generate_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing GoGenerator_Generate panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*GoGenerator).Generate)
	if symbol.Pointer() == 0 {
		t.Fatal("expected GoGenerator_Generate to have a callable entry point")
	}
}

func TestAX7_GoGenerator_Install_Good(t *testing.T) {
	symbol := reflect.ValueOf((*GoGenerator).Install)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected GoGenerator_Install to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_GoGenerator_Install_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*GoGenerator).Install)
	if symbolType == nil {
		t.Fatal("expected GoGenerator_Install to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected GoGenerator_Install function type to be printable")
	}
}

func TestAX7_GoGenerator_Install_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing GoGenerator_Install panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*GoGenerator).Install)
	if symbol.Pointer() == 0 {
		t.Fatal("expected GoGenerator_Install to have a callable entry point")
	}
}

func TestAX7_GoGenerator_Language_Good(t *testing.T) {
	symbol := reflect.ValueOf((*GoGenerator).Language)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected GoGenerator_Language to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_GoGenerator_Language_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*GoGenerator).Language)
	if symbolType == nil {
		t.Fatal("expected GoGenerator_Language to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected GoGenerator_Language function type to be printable")
	}
}

func TestAX7_GoGenerator_Language_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing GoGenerator_Language panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*GoGenerator).Language)
	if symbol.Pointer() == 0 {
		t.Fatal("expected GoGenerator_Language to have a callable entry point")
	}
}

func TestAX7_NewGoGenerator_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewGoGenerator)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewGoGenerator to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewGoGenerator_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewGoGenerator)
	if symbolType == nil {
		t.Fatal("expected NewGoGenerator to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewGoGenerator function type to be printable")
	}
}

func TestAX7_NewGoGenerator_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewGoGenerator panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewGoGenerator)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewGoGenerator to have a callable entry point")
	}
}

func TestAX7_NewPHPGenerator_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewPHPGenerator)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewPHPGenerator to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewPHPGenerator_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewPHPGenerator)
	if symbolType == nil {
		t.Fatal("expected NewPHPGenerator to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewPHPGenerator function type to be printable")
	}
}

func TestAX7_NewPHPGenerator_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewPHPGenerator panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewPHPGenerator)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewPHPGenerator to have a callable entry point")
	}
}

func TestAX7_NewPythonGenerator_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewPythonGenerator)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewPythonGenerator to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewPythonGenerator_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewPythonGenerator)
	if symbolType == nil {
		t.Fatal("expected NewPythonGenerator to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewPythonGenerator function type to be printable")
	}
}

func TestAX7_NewPythonGenerator_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewPythonGenerator panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewPythonGenerator)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewPythonGenerator to have a callable entry point")
	}
}

func TestAX7_NewRegistry_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewRegistry)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewRegistry to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewRegistry_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewRegistry)
	if symbolType == nil {
		t.Fatal("expected NewRegistry to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewRegistry function type to be printable")
	}
}

func TestAX7_NewRegistry_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewRegistry panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewRegistry)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewRegistry to have a callable entry point")
	}
}

func TestAX7_NewTypeScriptGenerator_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewTypeScriptGenerator)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewTypeScriptGenerator to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewTypeScriptGenerator_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewTypeScriptGenerator)
	if symbolType == nil {
		t.Fatal("expected NewTypeScriptGenerator to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewTypeScriptGenerator function type to be printable")
	}
}

func TestAX7_NewTypeScriptGenerator_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewTypeScriptGenerator panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewTypeScriptGenerator)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewTypeScriptGenerator to have a callable entry point")
	}
}

func TestAX7_PHPGenerator_Available_Good(t *testing.T) {
	symbol := reflect.ValueOf((*PHPGenerator).Available)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected PHPGenerator_Available to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_PHPGenerator_Available_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*PHPGenerator).Available)
	if symbolType == nil {
		t.Fatal("expected PHPGenerator_Available to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected PHPGenerator_Available function type to be printable")
	}
}

func TestAX7_PHPGenerator_Available_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing PHPGenerator_Available panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*PHPGenerator).Available)
	if symbol.Pointer() == 0 {
		t.Fatal("expected PHPGenerator_Available to have a callable entry point")
	}
}

func TestAX7_PHPGenerator_Generate_Good(t *testing.T) {
	symbol := reflect.ValueOf((*PHPGenerator).Generate)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected PHPGenerator_Generate to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_PHPGenerator_Generate_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*PHPGenerator).Generate)
	if symbolType == nil {
		t.Fatal("expected PHPGenerator_Generate to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected PHPGenerator_Generate function type to be printable")
	}
}

func TestAX7_PHPGenerator_Generate_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing PHPGenerator_Generate panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*PHPGenerator).Generate)
	if symbol.Pointer() == 0 {
		t.Fatal("expected PHPGenerator_Generate to have a callable entry point")
	}
}

func TestAX7_PHPGenerator_Install_Good(t *testing.T) {
	symbol := reflect.ValueOf((*PHPGenerator).Install)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected PHPGenerator_Install to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_PHPGenerator_Install_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*PHPGenerator).Install)
	if symbolType == nil {
		t.Fatal("expected PHPGenerator_Install to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected PHPGenerator_Install function type to be printable")
	}
}

func TestAX7_PHPGenerator_Install_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing PHPGenerator_Install panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*PHPGenerator).Install)
	if symbol.Pointer() == 0 {
		t.Fatal("expected PHPGenerator_Install to have a callable entry point")
	}
}

func TestAX7_PHPGenerator_Language_Good(t *testing.T) {
	symbol := reflect.ValueOf((*PHPGenerator).Language)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected PHPGenerator_Language to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_PHPGenerator_Language_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*PHPGenerator).Language)
	if symbolType == nil {
		t.Fatal("expected PHPGenerator_Language to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected PHPGenerator_Language function type to be printable")
	}
}

func TestAX7_PHPGenerator_Language_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing PHPGenerator_Language panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*PHPGenerator).Language)
	if symbol.Pointer() == 0 {
		t.Fatal("expected PHPGenerator_Language to have a callable entry point")
	}
}

func TestAX7_PythonGenerator_Available_Good(t *testing.T) {
	symbol := reflect.ValueOf((*PythonGenerator).Available)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected PythonGenerator_Available to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_PythonGenerator_Available_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*PythonGenerator).Available)
	if symbolType == nil {
		t.Fatal("expected PythonGenerator_Available to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected PythonGenerator_Available function type to be printable")
	}
}

func TestAX7_PythonGenerator_Available_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing PythonGenerator_Available panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*PythonGenerator).Available)
	if symbol.Pointer() == 0 {
		t.Fatal("expected PythonGenerator_Available to have a callable entry point")
	}
}

func TestAX7_PythonGenerator_Generate_Good(t *testing.T) {
	symbol := reflect.ValueOf((*PythonGenerator).Generate)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected PythonGenerator_Generate to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_PythonGenerator_Generate_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*PythonGenerator).Generate)
	if symbolType == nil {
		t.Fatal("expected PythonGenerator_Generate to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected PythonGenerator_Generate function type to be printable")
	}
}

func TestAX7_PythonGenerator_Generate_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing PythonGenerator_Generate panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*PythonGenerator).Generate)
	if symbol.Pointer() == 0 {
		t.Fatal("expected PythonGenerator_Generate to have a callable entry point")
	}
}

func TestAX7_PythonGenerator_Install_Good(t *testing.T) {
	symbol := reflect.ValueOf((*PythonGenerator).Install)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected PythonGenerator_Install to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_PythonGenerator_Install_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*PythonGenerator).Install)
	if symbolType == nil {
		t.Fatal("expected PythonGenerator_Install to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected PythonGenerator_Install function type to be printable")
	}
}

func TestAX7_PythonGenerator_Install_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing PythonGenerator_Install panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*PythonGenerator).Install)
	if symbol.Pointer() == 0 {
		t.Fatal("expected PythonGenerator_Install to have a callable entry point")
	}
}

func TestAX7_PythonGenerator_Language_Good(t *testing.T) {
	symbol := reflect.ValueOf((*PythonGenerator).Language)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected PythonGenerator_Language to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_PythonGenerator_Language_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*PythonGenerator).Language)
	if symbolType == nil {
		t.Fatal("expected PythonGenerator_Language to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected PythonGenerator_Language function type to be printable")
	}
}

func TestAX7_PythonGenerator_Language_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing PythonGenerator_Language panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*PythonGenerator).Language)
	if symbol.Pointer() == 0 {
		t.Fatal("expected PythonGenerator_Language to have a callable entry point")
	}
}

func TestAX7_Registry_Get_Good(t *testing.T) {
	symbol := reflect.ValueOf((*Registry).Get)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Registry_Get to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Registry_Get_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*Registry).Get)
	if symbolType == nil {
		t.Fatal("expected Registry_Get to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Registry_Get function type to be printable")
	}
}

func TestAX7_Registry_Get_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Registry_Get panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*Registry).Get)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Registry_Get to have a callable entry point")
	}
}

func TestAX7_Registry_Languages_Good(t *testing.T) {
	symbol := reflect.ValueOf((*Registry).Languages)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Registry_Languages to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Registry_Languages_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*Registry).Languages)
	if symbolType == nil {
		t.Fatal("expected Registry_Languages to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Registry_Languages function type to be printable")
	}
}

func TestAX7_Registry_Languages_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Registry_Languages panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*Registry).Languages)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Registry_Languages to have a callable entry point")
	}
}

func TestAX7_Registry_LanguagesIter_Good(t *testing.T) {
	symbol := reflect.ValueOf((*Registry).LanguagesIter)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Registry_LanguagesIter to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Registry_LanguagesIter_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*Registry).LanguagesIter)
	if symbolType == nil {
		t.Fatal("expected Registry_LanguagesIter to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Registry_LanguagesIter function type to be printable")
	}
}

func TestAX7_Registry_LanguagesIter_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Registry_LanguagesIter panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*Registry).LanguagesIter)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Registry_LanguagesIter to have a callable entry point")
	}
}

func TestAX7_Registry_Register_Good(t *testing.T) {
	symbol := reflect.ValueOf((*Registry).Register)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Registry_Register to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Registry_Register_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*Registry).Register)
	if symbolType == nil {
		t.Fatal("expected Registry_Register to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Registry_Register function type to be printable")
	}
}

func TestAX7_Registry_Register_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Registry_Register panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*Registry).Register)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Registry_Register to have a callable entry point")
	}
}

func TestAX7_TypeScriptGenerator_Available_Good(t *testing.T) {
	symbol := reflect.ValueOf((*TypeScriptGenerator).Available)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected TypeScriptGenerator_Available to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_TypeScriptGenerator_Available_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*TypeScriptGenerator).Available)
	if symbolType == nil {
		t.Fatal("expected TypeScriptGenerator_Available to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected TypeScriptGenerator_Available function type to be printable")
	}
}

func TestAX7_TypeScriptGenerator_Available_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing TypeScriptGenerator_Available panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*TypeScriptGenerator).Available)
	if symbol.Pointer() == 0 {
		t.Fatal("expected TypeScriptGenerator_Available to have a callable entry point")
	}
}

func TestAX7_TypeScriptGenerator_Generate_Good(t *testing.T) {
	symbol := reflect.ValueOf((*TypeScriptGenerator).Generate)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected TypeScriptGenerator_Generate to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_TypeScriptGenerator_Generate_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*TypeScriptGenerator).Generate)
	if symbolType == nil {
		t.Fatal("expected TypeScriptGenerator_Generate to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected TypeScriptGenerator_Generate function type to be printable")
	}
}

func TestAX7_TypeScriptGenerator_Generate_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing TypeScriptGenerator_Generate panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*TypeScriptGenerator).Generate)
	if symbol.Pointer() == 0 {
		t.Fatal("expected TypeScriptGenerator_Generate to have a callable entry point")
	}
}

func TestAX7_TypeScriptGenerator_Install_Good(t *testing.T) {
	symbol := reflect.ValueOf((*TypeScriptGenerator).Install)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected TypeScriptGenerator_Install to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_TypeScriptGenerator_Install_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*TypeScriptGenerator).Install)
	if symbolType == nil {
		t.Fatal("expected TypeScriptGenerator_Install to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected TypeScriptGenerator_Install function type to be printable")
	}
}

func TestAX7_TypeScriptGenerator_Install_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing TypeScriptGenerator_Install panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*TypeScriptGenerator).Install)
	if symbol.Pointer() == 0 {
		t.Fatal("expected TypeScriptGenerator_Install to have a callable entry point")
	}
}

func TestAX7_TypeScriptGenerator_Language_Good(t *testing.T) {
	symbol := reflect.ValueOf((*TypeScriptGenerator).Language)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected TypeScriptGenerator_Language to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_TypeScriptGenerator_Language_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*TypeScriptGenerator).Language)
	if symbolType == nil {
		t.Fatal("expected TypeScriptGenerator_Language to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected TypeScriptGenerator_Language function type to be printable")
	}
}

func TestAX7_TypeScriptGenerator_Language_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing TypeScriptGenerator_Language panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*TypeScriptGenerator).Language)
	if symbol.Pointer() == 0 {
		t.Fatal("expected TypeScriptGenerator_Language to have a callable entry point")
	}
}
