// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package sdk

import (
	"reflect"
	"testing"
)

func TestAX7_CloneConfig_Good(t *testing.T) {
	symbol := reflect.ValueOf(CloneConfig)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected CloneConfig to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_CloneConfig_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(CloneConfig)
	if symbolType == nil {
		t.Fatal("expected CloneConfig to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected CloneConfig function type to be printable")
	}
}

func TestAX7_CloneConfig_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing CloneConfig panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(CloneConfig)
	if symbol.Pointer() == 0 {
		t.Fatal("expected CloneConfig to have a callable entry point")
	}
}

func TestAX7_Config_ApplyDefaults_Good(t *testing.T) {
	symbol := reflect.ValueOf((*Config).ApplyDefaults)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Config_ApplyDefaults to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Config_ApplyDefaults_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*Config).ApplyDefaults)
	if symbolType == nil {
		t.Fatal("expected Config_ApplyDefaults to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Config_ApplyDefaults function type to be printable")
	}
}

func TestAX7_Config_ApplyDefaults_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Config_ApplyDefaults panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*Config).ApplyDefaults)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Config_ApplyDefaults to have a callable entry point")
	}
}

func TestAX7_DefaultConfig_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(DefaultConfig)
	if symbolType == nil {
		t.Fatal("expected DefaultConfig to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected DefaultConfig function type to be printable")
	}
}

func TestAX7_DefaultConfig_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DefaultConfig panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(DefaultConfig)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DefaultConfig to have a callable entry point")
	}
}

func TestAX7_Diff_Good(t *testing.T) {
	symbol := reflect.ValueOf(Diff)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Diff to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Diff_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Diff)
	if symbolType == nil {
		t.Fatal("expected Diff to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Diff function type to be printable")
	}
}

func TestAX7_Diff_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Diff panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Diff)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Diff to have a callable entry point")
	}
}

func TestAX7_DiffConfig_UnmarshalYAML_Good(t *testing.T) {
	symbol := reflect.ValueOf((*DiffConfig).UnmarshalYAML)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected DiffConfig_UnmarshalYAML to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_DiffConfig_UnmarshalYAML_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*DiffConfig).UnmarshalYAML)
	if symbolType == nil {
		t.Fatal("expected DiffConfig_UnmarshalYAML to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected DiffConfig_UnmarshalYAML function type to be printable")
	}
}

func TestAX7_DiffConfig_UnmarshalYAML_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DiffConfig_UnmarshalYAML panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*DiffConfig).UnmarshalYAML)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DiffConfig_UnmarshalYAML to have a callable entry point")
	}
}

func TestAX7_DiffExitCode_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(DiffExitCode)
	if symbolType == nil {
		t.Fatal("expected DiffExitCode to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected DiffExitCode function type to be printable")
	}
}

func TestAX7_DiffExitCode_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DiffExitCode panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(DiffExitCode)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DiffExitCode to have a callable entry point")
	}
}

func TestAX7_DiffWithOptions_Good(t *testing.T) {
	symbol := reflect.ValueOf(DiffWithOptions)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected DiffWithOptions to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_DiffWithOptions_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(DiffWithOptions)
	if symbolType == nil {
		t.Fatal("expected DiffWithOptions to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected DiffWithOptions function type to be printable")
	}
}

func TestAX7_DiffWithOptions_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DiffWithOptions panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(DiffWithOptions)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DiffWithOptions to have a callable entry point")
	}
}

func TestAX7_New_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(New)
	if symbolType == nil {
		t.Fatal("expected New to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected New function type to be printable")
	}
}

func TestAX7_New_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing New panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(New)
	if symbol.Pointer() == 0 {
		t.Fatal("expected New to have a callable entry point")
	}
}

func TestAX7_SDK_Config_Good(t *testing.T) {
	symbol := reflect.ValueOf((*SDK).Config)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected SDK_Config to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_SDK_Config_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*SDK).Config)
	if symbolType == nil {
		t.Fatal("expected SDK_Config to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected SDK_Config function type to be printable")
	}
}

func TestAX7_SDK_Config_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing SDK_Config panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*SDK).Config)
	if symbol.Pointer() == 0 {
		t.Fatal("expected SDK_Config to have a callable entry point")
	}
}

func TestAX7_SDK_DetectSpec_Good(t *testing.T) {
	symbol := reflect.ValueOf((*SDK).DetectSpec)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected SDK_DetectSpec to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_SDK_DetectSpec_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*SDK).DetectSpec)
	if symbolType == nil {
		t.Fatal("expected SDK_DetectSpec to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected SDK_DetectSpec function type to be printable")
	}
}

func TestAX7_SDK_DetectSpec_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing SDK_DetectSpec panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*SDK).DetectSpec)
	if symbol.Pointer() == 0 {
		t.Fatal("expected SDK_DetectSpec to have a callable entry point")
	}
}

func TestAX7_SDK_Generate_Good(t *testing.T) {
	symbol := reflect.ValueOf((*SDK).Generate)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected SDK_Generate to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_SDK_Generate_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*SDK).Generate)
	if symbolType == nil {
		t.Fatal("expected SDK_Generate to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected SDK_Generate function type to be printable")
	}
}

func TestAX7_SDK_Generate_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing SDK_Generate panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*SDK).Generate)
	if symbol.Pointer() == 0 {
		t.Fatal("expected SDK_Generate to have a callable entry point")
	}
}

func TestAX7_SDK_GenerateLanguage_Good(t *testing.T) {
	symbol := reflect.ValueOf((*SDK).GenerateLanguage)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected SDK_GenerateLanguage to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_SDK_GenerateLanguage_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*SDK).GenerateLanguage)
	if symbolType == nil {
		t.Fatal("expected SDK_GenerateLanguage to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected SDK_GenerateLanguage function type to be printable")
	}
}

func TestAX7_SDK_GenerateLanguage_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing SDK_GenerateLanguage panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*SDK).GenerateLanguage)
	if symbol.Pointer() == 0 {
		t.Fatal("expected SDK_GenerateLanguage to have a callable entry point")
	}
}

func TestAX7_SDK_GenerateLanguageWithStatus_Good(t *testing.T) {
	symbol := reflect.ValueOf((*SDK).GenerateLanguageWithStatus)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected SDK_GenerateLanguageWithStatus to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_SDK_GenerateLanguageWithStatus_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*SDK).GenerateLanguageWithStatus)
	if symbolType == nil {
		t.Fatal("expected SDK_GenerateLanguageWithStatus to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected SDK_GenerateLanguageWithStatus function type to be printable")
	}
}

func TestAX7_SDK_GenerateLanguageWithStatus_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing SDK_GenerateLanguageWithStatus panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*SDK).GenerateLanguageWithStatus)
	if symbol.Pointer() == 0 {
		t.Fatal("expected SDK_GenerateLanguageWithStatus to have a callable entry point")
	}
}

func TestAX7_SDK_GenerateWithStatus_Good(t *testing.T) {
	symbol := reflect.ValueOf((*SDK).GenerateWithStatus)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected SDK_GenerateWithStatus to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_SDK_GenerateWithStatus_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*SDK).GenerateWithStatus)
	if symbolType == nil {
		t.Fatal("expected SDK_GenerateWithStatus to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected SDK_GenerateWithStatus function type to be printable")
	}
}

func TestAX7_SDK_GenerateWithStatus_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing SDK_GenerateWithStatus panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*SDK).GenerateWithStatus)
	if symbol.Pointer() == 0 {
		t.Fatal("expected SDK_GenerateWithStatus to have a callable entry point")
	}
}

func TestAX7_SDK_SetVersion_Good(t *testing.T) {
	symbol := reflect.ValueOf((*SDK).SetVersion)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected SDK_SetVersion to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_SDK_SetVersion_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*SDK).SetVersion)
	if symbolType == nil {
		t.Fatal("expected SDK_SetVersion to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected SDK_SetVersion function type to be printable")
	}
}

func TestAX7_SDK_SetVersion_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing SDK_SetVersion panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*SDK).SetVersion)
	if symbol.Pointer() == 0 {
		t.Fatal("expected SDK_SetVersion to have a callable entry point")
	}
}

func TestAX7_SDK_ValidateSpec_Good(t *testing.T) {
	symbol := reflect.ValueOf((*SDK).ValidateSpec)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected SDK_ValidateSpec to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_SDK_ValidateSpec_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*SDK).ValidateSpec)
	if symbolType == nil {
		t.Fatal("expected SDK_ValidateSpec to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected SDK_ValidateSpec function type to be printable")
	}
}

func TestAX7_SDK_ValidateSpec_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing SDK_ValidateSpec panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*SDK).ValidateSpec)
	if symbol.Pointer() == 0 {
		t.Fatal("expected SDK_ValidateSpec to have a callable entry point")
	}
}
