// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package ci

import (
	"reflect"
	"testing"
)

func TestAX7_AddCICommands_Good(t *testing.T) {
	symbol := reflect.ValueOf(AddCICommands)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected AddCICommands to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_AddCICommands_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(AddCICommands)
	if symbolType == nil {
		t.Fatal("expected AddCICommands to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected AddCICommands function type to be printable")
	}
}

func TestAX7_AddCICommands_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing AddCICommands panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(AddCICommands)
	if symbol.Pointer() == 0 {
		t.Fatal("expected AddCICommands to have a callable entry point")
	}
}
