// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package sdkcmd

import (
	"reflect"
	"testing"
)

func TestAX7_AddSDKCommands_Good(t *testing.T) {
	symbol := reflect.ValueOf(AddSDKCommands)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected AddSDKCommands to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_AddSDKCommands_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(AddSDKCommands)
	if symbolType == nil {
		t.Fatal("expected AddSDKCommands to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected AddSDKCommands function type to be printable")
	}
}

func TestAX7_AddSDKCommands_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing AddSDKCommands panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(AddSDKCommands)
	if symbol.Pointer() == 0 {
		t.Fatal("expected AddSDKCommands to have a callable entry point")
	}
}
