// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package cmdutil

import (
	"reflect"
	"testing"
)

func TestAX7_ContextOrBackground_Good(t *testing.T) {
	symbol := reflect.ValueOf(ContextOrBackground)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ContextOrBackground to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ContextOrBackground_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ContextOrBackground)
	if symbolType == nil {
		t.Fatal("expected ContextOrBackground to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ContextOrBackground function type to be printable")
	}
}

func TestAX7_ContextOrBackground_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ContextOrBackground panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ContextOrBackground)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ContextOrBackground to have a callable entry point")
	}
}

func TestAX7_OptionBool_Good(t *testing.T) {
	symbol := reflect.ValueOf(OptionBool)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected OptionBool to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_OptionBool_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(OptionBool)
	if symbolType == nil {
		t.Fatal("expected OptionBool to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected OptionBool function type to be printable")
	}
}

func TestAX7_OptionBool_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing OptionBool panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(OptionBool)
	if symbol.Pointer() == 0 {
		t.Fatal("expected OptionBool to have a callable entry point")
	}
}

func TestAX7_OptionBoolDefault_Good(t *testing.T) {
	symbol := reflect.ValueOf(OptionBoolDefault)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected OptionBoolDefault to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_OptionBoolDefault_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(OptionBoolDefault)
	if symbolType == nil {
		t.Fatal("expected OptionBoolDefault to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected OptionBoolDefault function type to be printable")
	}
}

func TestAX7_OptionBoolDefault_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing OptionBoolDefault panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(OptionBoolDefault)
	if symbol.Pointer() == 0 {
		t.Fatal("expected OptionBoolDefault to have a callable entry point")
	}
}

func TestAX7_OptionHas_Good(t *testing.T) {
	symbol := reflect.ValueOf(OptionHas)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected OptionHas to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_OptionHas_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(OptionHas)
	if symbolType == nil {
		t.Fatal("expected OptionHas to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected OptionHas function type to be printable")
	}
}

func TestAX7_OptionHas_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing OptionHas panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(OptionHas)
	if symbol.Pointer() == 0 {
		t.Fatal("expected OptionHas to have a callable entry point")
	}
}

func TestAX7_OptionString_Good(t *testing.T) {
	symbol := reflect.ValueOf(OptionString)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected OptionString to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_OptionString_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(OptionString)
	if symbolType == nil {
		t.Fatal("expected OptionString to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected OptionString function type to be printable")
	}
}

func TestAX7_OptionString_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing OptionString panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(OptionString)
	if symbol.Pointer() == 0 {
		t.Fatal("expected OptionString to have a callable entry point")
	}
}

func TestAX7_ResultFromError_Good(t *testing.T) {
	symbol := reflect.ValueOf(ResultFromError)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ResultFromError to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ResultFromError_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ResultFromError)
	if symbolType == nil {
		t.Fatal("expected ResultFromError to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ResultFromError function type to be printable")
	}
}

func TestAX7_ResultFromError_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ResultFromError panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ResultFromError)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ResultFromError to have a callable entry point")
	}
}
