// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package servicecmd

import (
	"reflect"
	"testing"
)

func TestAX7_ApplyOverrides_Good(t *testing.T) {
	symbol := reflect.ValueOf(ApplyOverrides)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ApplyOverrides to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ApplyOverrides_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ApplyOverrides)
	if symbolType == nil {
		t.Fatal("expected ApplyOverrides to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ApplyOverrides function type to be printable")
	}
}

func TestAX7_ApplyOverrides_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ApplyOverrides panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ApplyOverrides)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ApplyOverrides to have a callable entry point")
	}
}

func TestAX7_FromOptions_Good(t *testing.T) {
	symbol := reflect.ValueOf(FromOptions)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected FromOptions to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_FromOptions_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(FromOptions)
	if symbolType == nil {
		t.Fatal("expected FromOptions to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected FromOptions function type to be printable")
	}
}

func TestAX7_FromOptions_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing FromOptions panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(FromOptions)
	if symbol.Pointer() == 0 {
		t.Fatal("expected FromOptions to have a callable entry point")
	}
}

func TestAX7_LoadConfig_Good(t *testing.T) {
	symbol := reflect.ValueOf(LoadConfig)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected LoadConfig to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_LoadConfig_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(LoadConfig)
	if symbolType == nil {
		t.Fatal("expected LoadConfig to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected LoadConfig function type to be printable")
	}
}

func TestAX7_LoadConfig_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing LoadConfig panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(LoadConfig)
	if symbol.Pointer() == 0 {
		t.Fatal("expected LoadConfig to have a callable entry point")
	}
}

func TestAX7_ParseCSV_Good(t *testing.T) {
	symbol := reflect.ValueOf(ParseCSV)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ParseCSV to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ParseCSV_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ParseCSV)
	if symbolType == nil {
		t.Fatal("expected ParseCSV to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ParseCSV function type to be printable")
	}
}

func TestAX7_ParseCSV_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ParseCSV panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ParseCSV)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ParseCSV to have a callable entry point")
	}
}
