// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package buildtest

import (
	"reflect"
	"testing"
)

func TestAX7_AssertReleaseWorkflowContent_Good(t *testing.T) {
	symbol := reflect.ValueOf(AssertReleaseWorkflowContent)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected AssertReleaseWorkflowContent to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_AssertReleaseWorkflowContent_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(AssertReleaseWorkflowContent)
	if symbolType == nil {
		t.Fatal("expected AssertReleaseWorkflowContent to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected AssertReleaseWorkflowContent function type to be printable")
	}
}

func TestAX7_AssertReleaseWorkflowContent_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing AssertReleaseWorkflowContent panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(AssertReleaseWorkflowContent)
	if symbol.Pointer() == 0 {
		t.Fatal("expected AssertReleaseWorkflowContent to have a callable entry point")
	}
}

func TestAX7_AssertReleaseWorkflowTriggers_Good(t *testing.T) {
	symbol := reflect.ValueOf(AssertReleaseWorkflowTriggers)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected AssertReleaseWorkflowTriggers to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_AssertReleaseWorkflowTriggers_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(AssertReleaseWorkflowTriggers)
	if symbolType == nil {
		t.Fatal("expected AssertReleaseWorkflowTriggers to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected AssertReleaseWorkflowTriggers function type to be printable")
	}
}

func TestAX7_AssertReleaseWorkflowTriggers_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing AssertReleaseWorkflowTriggers panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(AssertReleaseWorkflowTriggers)
	if symbol.Pointer() == 0 {
		t.Fatal("expected AssertReleaseWorkflowTriggers to have a callable entry point")
	}
}
