// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package publishers

import (
	"reflect"
	"testing"
)

func TestAX7_AURPublisher_Name_Good(t *testing.T) {
	symbol := reflect.ValueOf((*AURPublisher).Name)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected AURPublisher_Name to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_AURPublisher_Name_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*AURPublisher).Name)
	if symbolType == nil {
		t.Fatal("expected AURPublisher_Name to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected AURPublisher_Name function type to be printable")
	}
}

func TestAX7_AURPublisher_Name_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing AURPublisher_Name panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*AURPublisher).Name)
	if symbol.Pointer() == 0 {
		t.Fatal("expected AURPublisher_Name to have a callable entry point")
	}
}

func TestAX7_AURPublisher_Publish_Good(t *testing.T) {
	symbol := reflect.ValueOf((*AURPublisher).Publish)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected AURPublisher_Publish to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_AURPublisher_Publish_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*AURPublisher).Publish)
	if symbolType == nil {
		t.Fatal("expected AURPublisher_Publish to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected AURPublisher_Publish function type to be printable")
	}
}

func TestAX7_AURPublisher_Publish_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing AURPublisher_Publish panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*AURPublisher).Publish)
	if symbol.Pointer() == 0 {
		t.Fatal("expected AURPublisher_Publish to have a callable entry point")
	}
}

func TestAX7_AURPublisher_Supports_Good(t *testing.T) {
	symbol := reflect.ValueOf((*AURPublisher).Supports)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected AURPublisher_Supports to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_AURPublisher_Supports_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*AURPublisher).Supports)
	if symbolType == nil {
		t.Fatal("expected AURPublisher_Supports to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected AURPublisher_Supports function type to be printable")
	}
}

func TestAX7_AURPublisher_Supports_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing AURPublisher_Supports panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*AURPublisher).Supports)
	if symbol.Pointer() == 0 {
		t.Fatal("expected AURPublisher_Supports to have a callable entry point")
	}
}

func TestAX7_AURPublisher_Validate_Good(t *testing.T) {
	symbol := reflect.ValueOf((*AURPublisher).Validate)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected AURPublisher_Validate to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_AURPublisher_Validate_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*AURPublisher).Validate)
	if symbolType == nil {
		t.Fatal("expected AURPublisher_Validate to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected AURPublisher_Validate function type to be printable")
	}
}

func TestAX7_AURPublisher_Validate_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing AURPublisher_Validate panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*AURPublisher).Validate)
	if symbol.Pointer() == 0 {
		t.Fatal("expected AURPublisher_Validate to have a callable entry point")
	}
}

func TestAX7_ChocolateyPublisher_Name_Good(t *testing.T) {
	symbol := reflect.ValueOf((*ChocolateyPublisher).Name)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ChocolateyPublisher_Name to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ChocolateyPublisher_Name_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*ChocolateyPublisher).Name)
	if symbolType == nil {
		t.Fatal("expected ChocolateyPublisher_Name to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ChocolateyPublisher_Name function type to be printable")
	}
}

func TestAX7_ChocolateyPublisher_Name_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ChocolateyPublisher_Name panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*ChocolateyPublisher).Name)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ChocolateyPublisher_Name to have a callable entry point")
	}
}

func TestAX7_ChocolateyPublisher_Publish_Good(t *testing.T) {
	symbol := reflect.ValueOf((*ChocolateyPublisher).Publish)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ChocolateyPublisher_Publish to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ChocolateyPublisher_Publish_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*ChocolateyPublisher).Publish)
	if symbolType == nil {
		t.Fatal("expected ChocolateyPublisher_Publish to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ChocolateyPublisher_Publish function type to be printable")
	}
}

func TestAX7_ChocolateyPublisher_Publish_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ChocolateyPublisher_Publish panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*ChocolateyPublisher).Publish)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ChocolateyPublisher_Publish to have a callable entry point")
	}
}

func TestAX7_ChocolateyPublisher_Supports_Good(t *testing.T) {
	symbol := reflect.ValueOf((*ChocolateyPublisher).Supports)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ChocolateyPublisher_Supports to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ChocolateyPublisher_Supports_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*ChocolateyPublisher).Supports)
	if symbolType == nil {
		t.Fatal("expected ChocolateyPublisher_Supports to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ChocolateyPublisher_Supports function type to be printable")
	}
}

func TestAX7_ChocolateyPublisher_Supports_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ChocolateyPublisher_Supports panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*ChocolateyPublisher).Supports)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ChocolateyPublisher_Supports to have a callable entry point")
	}
}

func TestAX7_ChocolateyPublisher_Validate_Good(t *testing.T) {
	symbol := reflect.ValueOf((*ChocolateyPublisher).Validate)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ChocolateyPublisher_Validate to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ChocolateyPublisher_Validate_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*ChocolateyPublisher).Validate)
	if symbolType == nil {
		t.Fatal("expected ChocolateyPublisher_Validate to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ChocolateyPublisher_Validate function type to be printable")
	}
}

func TestAX7_ChocolateyPublisher_Validate_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ChocolateyPublisher_Validate panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*ChocolateyPublisher).Validate)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ChocolateyPublisher_Validate to have a callable entry point")
	}
}

func TestAX7_DeleteRelease_Good(t *testing.T) {
	symbol := reflect.ValueOf(DeleteRelease)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected DeleteRelease to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_DeleteRelease_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(DeleteRelease)
	if symbolType == nil {
		t.Fatal("expected DeleteRelease to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected DeleteRelease function type to be printable")
	}
}

func TestAX7_DeleteRelease_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DeleteRelease panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(DeleteRelease)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DeleteRelease to have a callable entry point")
	}
}

func TestAX7_DetectGitHubRepository_Good(t *testing.T) {
	symbol := reflect.ValueOf(DetectGitHubRepository)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected DetectGitHubRepository to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_DetectGitHubRepository_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(DetectGitHubRepository)
	if symbolType == nil {
		t.Fatal("expected DetectGitHubRepository to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected DetectGitHubRepository function type to be printable")
	}
}

func TestAX7_DetectGitHubRepository_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DetectGitHubRepository panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(DetectGitHubRepository)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DetectGitHubRepository to have a callable entry point")
	}
}

func TestAX7_DockerPublisher_Name_Good(t *testing.T) {
	symbol := reflect.ValueOf((*DockerPublisher).Name)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected DockerPublisher_Name to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_DockerPublisher_Name_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*DockerPublisher).Name)
	if symbolType == nil {
		t.Fatal("expected DockerPublisher_Name to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected DockerPublisher_Name function type to be printable")
	}
}

func TestAX7_DockerPublisher_Name_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DockerPublisher_Name panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*DockerPublisher).Name)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DockerPublisher_Name to have a callable entry point")
	}
}

func TestAX7_DockerPublisher_Publish_Good(t *testing.T) {
	symbol := reflect.ValueOf((*DockerPublisher).Publish)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected DockerPublisher_Publish to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_DockerPublisher_Publish_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*DockerPublisher).Publish)
	if symbolType == nil {
		t.Fatal("expected DockerPublisher_Publish to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected DockerPublisher_Publish function type to be printable")
	}
}

func TestAX7_DockerPublisher_Publish_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DockerPublisher_Publish panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*DockerPublisher).Publish)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DockerPublisher_Publish to have a callable entry point")
	}
}

func TestAX7_DockerPublisher_Supports_Good(t *testing.T) {
	symbol := reflect.ValueOf((*DockerPublisher).Supports)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected DockerPublisher_Supports to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_DockerPublisher_Supports_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*DockerPublisher).Supports)
	if symbolType == nil {
		t.Fatal("expected DockerPublisher_Supports to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected DockerPublisher_Supports function type to be printable")
	}
}

func TestAX7_DockerPublisher_Supports_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DockerPublisher_Supports panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*DockerPublisher).Supports)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DockerPublisher_Supports to have a callable entry point")
	}
}

func TestAX7_DockerPublisher_Validate_Good(t *testing.T) {
	symbol := reflect.ValueOf((*DockerPublisher).Validate)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected DockerPublisher_Validate to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_DockerPublisher_Validate_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*DockerPublisher).Validate)
	if symbolType == nil {
		t.Fatal("expected DockerPublisher_Validate to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected DockerPublisher_Validate function type to be printable")
	}
}

func TestAX7_DockerPublisher_Validate_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DockerPublisher_Validate panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*DockerPublisher).Validate)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DockerPublisher_Validate to have a callable entry point")
	}
}

func TestAX7_GitHubPublisher_Name_Good(t *testing.T) {
	symbol := reflect.ValueOf((*GitHubPublisher).Name)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected GitHubPublisher_Name to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_GitHubPublisher_Name_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*GitHubPublisher).Name)
	if symbolType == nil {
		t.Fatal("expected GitHubPublisher_Name to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected GitHubPublisher_Name function type to be printable")
	}
}

func TestAX7_GitHubPublisher_Name_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing GitHubPublisher_Name panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*GitHubPublisher).Name)
	if symbol.Pointer() == 0 {
		t.Fatal("expected GitHubPublisher_Name to have a callable entry point")
	}
}

func TestAX7_GitHubPublisher_Publish_Good(t *testing.T) {
	symbol := reflect.ValueOf((*GitHubPublisher).Publish)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected GitHubPublisher_Publish to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_GitHubPublisher_Publish_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*GitHubPublisher).Publish)
	if symbolType == nil {
		t.Fatal("expected GitHubPublisher_Publish to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected GitHubPublisher_Publish function type to be printable")
	}
}

func TestAX7_GitHubPublisher_Publish_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing GitHubPublisher_Publish panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*GitHubPublisher).Publish)
	if symbol.Pointer() == 0 {
		t.Fatal("expected GitHubPublisher_Publish to have a callable entry point")
	}
}

func TestAX7_GitHubPublisher_Supports_Good(t *testing.T) {
	symbol := reflect.ValueOf((*GitHubPublisher).Supports)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected GitHubPublisher_Supports to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_GitHubPublisher_Supports_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*GitHubPublisher).Supports)
	if symbolType == nil {
		t.Fatal("expected GitHubPublisher_Supports to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected GitHubPublisher_Supports function type to be printable")
	}
}

func TestAX7_GitHubPublisher_Supports_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing GitHubPublisher_Supports panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*GitHubPublisher).Supports)
	if symbol.Pointer() == 0 {
		t.Fatal("expected GitHubPublisher_Supports to have a callable entry point")
	}
}

func TestAX7_GitHubPublisher_Validate_Good(t *testing.T) {
	symbol := reflect.ValueOf((*GitHubPublisher).Validate)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected GitHubPublisher_Validate to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_GitHubPublisher_Validate_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*GitHubPublisher).Validate)
	if symbolType == nil {
		t.Fatal("expected GitHubPublisher_Validate to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected GitHubPublisher_Validate function type to be printable")
	}
}

func TestAX7_GitHubPublisher_Validate_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing GitHubPublisher_Validate panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*GitHubPublisher).Validate)
	if symbol.Pointer() == 0 {
		t.Fatal("expected GitHubPublisher_Validate to have a callable entry point")
	}
}

func TestAX7_HomebrewPublisher_Name_Good(t *testing.T) {
	symbol := reflect.ValueOf((*HomebrewPublisher).Name)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected HomebrewPublisher_Name to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_HomebrewPublisher_Name_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*HomebrewPublisher).Name)
	if symbolType == nil {
		t.Fatal("expected HomebrewPublisher_Name to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected HomebrewPublisher_Name function type to be printable")
	}
}

func TestAX7_HomebrewPublisher_Name_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing HomebrewPublisher_Name panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*HomebrewPublisher).Name)
	if symbol.Pointer() == 0 {
		t.Fatal("expected HomebrewPublisher_Name to have a callable entry point")
	}
}

func TestAX7_HomebrewPublisher_Publish_Good(t *testing.T) {
	symbol := reflect.ValueOf((*HomebrewPublisher).Publish)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected HomebrewPublisher_Publish to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_HomebrewPublisher_Publish_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*HomebrewPublisher).Publish)
	if symbolType == nil {
		t.Fatal("expected HomebrewPublisher_Publish to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected HomebrewPublisher_Publish function type to be printable")
	}
}

func TestAX7_HomebrewPublisher_Publish_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing HomebrewPublisher_Publish panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*HomebrewPublisher).Publish)
	if symbol.Pointer() == 0 {
		t.Fatal("expected HomebrewPublisher_Publish to have a callable entry point")
	}
}

func TestAX7_HomebrewPublisher_Supports_Good(t *testing.T) {
	symbol := reflect.ValueOf((*HomebrewPublisher).Supports)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected HomebrewPublisher_Supports to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_HomebrewPublisher_Supports_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*HomebrewPublisher).Supports)
	if symbolType == nil {
		t.Fatal("expected HomebrewPublisher_Supports to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected HomebrewPublisher_Supports function type to be printable")
	}
}

func TestAX7_HomebrewPublisher_Supports_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing HomebrewPublisher_Supports panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*HomebrewPublisher).Supports)
	if symbol.Pointer() == 0 {
		t.Fatal("expected HomebrewPublisher_Supports to have a callable entry point")
	}
}

func TestAX7_HomebrewPublisher_Validate_Good(t *testing.T) {
	symbol := reflect.ValueOf((*HomebrewPublisher).Validate)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected HomebrewPublisher_Validate to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_HomebrewPublisher_Validate_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*HomebrewPublisher).Validate)
	if symbolType == nil {
		t.Fatal("expected HomebrewPublisher_Validate to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected HomebrewPublisher_Validate function type to be printable")
	}
}

func TestAX7_HomebrewPublisher_Validate_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing HomebrewPublisher_Validate panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*HomebrewPublisher).Validate)
	if symbol.Pointer() == 0 {
		t.Fatal("expected HomebrewPublisher_Validate to have a callable entry point")
	}
}

func TestAX7_LinuxKitPublisher_Name_Good(t *testing.T) {
	symbol := reflect.ValueOf((*LinuxKitPublisher).Name)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected LinuxKitPublisher_Name to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_LinuxKitPublisher_Name_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*LinuxKitPublisher).Name)
	if symbolType == nil {
		t.Fatal("expected LinuxKitPublisher_Name to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected LinuxKitPublisher_Name function type to be printable")
	}
}

func TestAX7_LinuxKitPublisher_Name_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing LinuxKitPublisher_Name panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*LinuxKitPublisher).Name)
	if symbol.Pointer() == 0 {
		t.Fatal("expected LinuxKitPublisher_Name to have a callable entry point")
	}
}

func TestAX7_LinuxKitPublisher_Publish_Good(t *testing.T) {
	symbol := reflect.ValueOf((*LinuxKitPublisher).Publish)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected LinuxKitPublisher_Publish to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_LinuxKitPublisher_Publish_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*LinuxKitPublisher).Publish)
	if symbolType == nil {
		t.Fatal("expected LinuxKitPublisher_Publish to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected LinuxKitPublisher_Publish function type to be printable")
	}
}

func TestAX7_LinuxKitPublisher_Publish_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing LinuxKitPublisher_Publish panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*LinuxKitPublisher).Publish)
	if symbol.Pointer() == 0 {
		t.Fatal("expected LinuxKitPublisher_Publish to have a callable entry point")
	}
}

func TestAX7_LinuxKitPublisher_Supports_Good(t *testing.T) {
	symbol := reflect.ValueOf((*LinuxKitPublisher).Supports)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected LinuxKitPublisher_Supports to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_LinuxKitPublisher_Supports_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*LinuxKitPublisher).Supports)
	if symbolType == nil {
		t.Fatal("expected LinuxKitPublisher_Supports to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected LinuxKitPublisher_Supports function type to be printable")
	}
}

func TestAX7_LinuxKitPublisher_Supports_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing LinuxKitPublisher_Supports panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*LinuxKitPublisher).Supports)
	if symbol.Pointer() == 0 {
		t.Fatal("expected LinuxKitPublisher_Supports to have a callable entry point")
	}
}

func TestAX7_LinuxKitPublisher_Validate_Good(t *testing.T) {
	symbol := reflect.ValueOf((*LinuxKitPublisher).Validate)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected LinuxKitPublisher_Validate to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_LinuxKitPublisher_Validate_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*LinuxKitPublisher).Validate)
	if symbolType == nil {
		t.Fatal("expected LinuxKitPublisher_Validate to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected LinuxKitPublisher_Validate function type to be printable")
	}
}

func TestAX7_LinuxKitPublisher_Validate_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing LinuxKitPublisher_Validate panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*LinuxKitPublisher).Validate)
	if symbol.Pointer() == 0 {
		t.Fatal("expected LinuxKitPublisher_Validate to have a callable entry point")
	}
}

func TestAX7_NewAURPublisher_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewAURPublisher)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewAURPublisher to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewAURPublisher_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewAURPublisher)
	if symbolType == nil {
		t.Fatal("expected NewAURPublisher to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewAURPublisher function type to be printable")
	}
}

func TestAX7_NewAURPublisher_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewAURPublisher panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewAURPublisher)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewAURPublisher to have a callable entry point")
	}
}

func TestAX7_NewChocolateyPublisher_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewChocolateyPublisher)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewChocolateyPublisher to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewChocolateyPublisher_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewChocolateyPublisher)
	if symbolType == nil {
		t.Fatal("expected NewChocolateyPublisher to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewChocolateyPublisher function type to be printable")
	}
}

func TestAX7_NewChocolateyPublisher_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewChocolateyPublisher panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewChocolateyPublisher)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewChocolateyPublisher to have a callable entry point")
	}
}

func TestAX7_NewDockerPublisher_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewDockerPublisher)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewDockerPublisher to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewDockerPublisher_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewDockerPublisher)
	if symbolType == nil {
		t.Fatal("expected NewDockerPublisher to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewDockerPublisher function type to be printable")
	}
}

func TestAX7_NewDockerPublisher_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewDockerPublisher panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewDockerPublisher)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewDockerPublisher to have a callable entry point")
	}
}

func TestAX7_NewGitHubPublisher_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewGitHubPublisher)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewGitHubPublisher to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewGitHubPublisher_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewGitHubPublisher)
	if symbolType == nil {
		t.Fatal("expected NewGitHubPublisher to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewGitHubPublisher function type to be printable")
	}
}

func TestAX7_NewGitHubPublisher_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewGitHubPublisher panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewGitHubPublisher)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewGitHubPublisher to have a callable entry point")
	}
}

func TestAX7_NewHomebrewPublisher_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewHomebrewPublisher)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewHomebrewPublisher to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewHomebrewPublisher_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewHomebrewPublisher)
	if symbolType == nil {
		t.Fatal("expected NewHomebrewPublisher to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewHomebrewPublisher function type to be printable")
	}
}

func TestAX7_NewHomebrewPublisher_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewHomebrewPublisher panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewHomebrewPublisher)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewHomebrewPublisher to have a callable entry point")
	}
}

func TestAX7_NewLinuxKitPublisher_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewLinuxKitPublisher)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewLinuxKitPublisher to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewLinuxKitPublisher_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewLinuxKitPublisher)
	if symbolType == nil {
		t.Fatal("expected NewLinuxKitPublisher to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewLinuxKitPublisher function type to be printable")
	}
}

func TestAX7_NewLinuxKitPublisher_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewLinuxKitPublisher panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewLinuxKitPublisher)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewLinuxKitPublisher to have a callable entry point")
	}
}

func TestAX7_NewNpmPublisher_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewNpmPublisher)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewNpmPublisher to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewNpmPublisher_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewNpmPublisher)
	if symbolType == nil {
		t.Fatal("expected NewNpmPublisher to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewNpmPublisher function type to be printable")
	}
}

func TestAX7_NewNpmPublisher_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewNpmPublisher panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewNpmPublisher)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewNpmPublisher to have a callable entry point")
	}
}

func TestAX7_NewPublisherConfig_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewPublisherConfig)
	if symbolType == nil {
		t.Fatal("expected NewPublisherConfig to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewPublisherConfig function type to be printable")
	}
}

func TestAX7_NewPublisherConfig_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewPublisherConfig panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewPublisherConfig)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewPublisherConfig to have a callable entry point")
	}
}

func TestAX7_NewRelease_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewRelease)
	if symbolType == nil {
		t.Fatal("expected NewRelease to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewRelease function type to be printable")
	}
}

func TestAX7_NewRelease_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewRelease panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewRelease)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewRelease to have a callable entry point")
	}
}

func TestAX7_NewReleaseWithArtifactFS_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewReleaseWithArtifactFS)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewReleaseWithArtifactFS to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewReleaseWithArtifactFS_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewReleaseWithArtifactFS)
	if symbolType == nil {
		t.Fatal("expected NewReleaseWithArtifactFS to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewReleaseWithArtifactFS function type to be printable")
	}
}

func TestAX7_NewReleaseWithArtifactFS_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewReleaseWithArtifactFS panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewReleaseWithArtifactFS)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewReleaseWithArtifactFS to have a callable entry point")
	}
}

func TestAX7_NewScoopPublisher_Good(t *testing.T) {
	symbol := reflect.ValueOf(NewScoopPublisher)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NewScoopPublisher to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NewScoopPublisher_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(NewScoopPublisher)
	if symbolType == nil {
		t.Fatal("expected NewScoopPublisher to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NewScoopPublisher function type to be printable")
	}
}

func TestAX7_NewScoopPublisher_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NewScoopPublisher panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(NewScoopPublisher)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NewScoopPublisher to have a callable entry point")
	}
}

func TestAX7_NpmPublisher_Name_Good(t *testing.T) {
	symbol := reflect.ValueOf((*NpmPublisher).Name)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NpmPublisher_Name to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NpmPublisher_Name_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*NpmPublisher).Name)
	if symbolType == nil {
		t.Fatal("expected NpmPublisher_Name to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NpmPublisher_Name function type to be printable")
	}
}

func TestAX7_NpmPublisher_Name_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NpmPublisher_Name panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*NpmPublisher).Name)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NpmPublisher_Name to have a callable entry point")
	}
}

func TestAX7_NpmPublisher_Publish_Good(t *testing.T) {
	symbol := reflect.ValueOf((*NpmPublisher).Publish)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NpmPublisher_Publish to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NpmPublisher_Publish_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*NpmPublisher).Publish)
	if symbolType == nil {
		t.Fatal("expected NpmPublisher_Publish to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NpmPublisher_Publish function type to be printable")
	}
}

func TestAX7_NpmPublisher_Publish_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NpmPublisher_Publish panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*NpmPublisher).Publish)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NpmPublisher_Publish to have a callable entry point")
	}
}

func TestAX7_NpmPublisher_Supports_Good(t *testing.T) {
	symbol := reflect.ValueOf((*NpmPublisher).Supports)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NpmPublisher_Supports to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NpmPublisher_Supports_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*NpmPublisher).Supports)
	if symbolType == nil {
		t.Fatal("expected NpmPublisher_Supports to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NpmPublisher_Supports function type to be printable")
	}
}

func TestAX7_NpmPublisher_Supports_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NpmPublisher_Supports panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*NpmPublisher).Supports)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NpmPublisher_Supports to have a callable entry point")
	}
}

func TestAX7_NpmPublisher_Validate_Good(t *testing.T) {
	symbol := reflect.ValueOf((*NpmPublisher).Validate)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected NpmPublisher_Validate to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_NpmPublisher_Validate_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*NpmPublisher).Validate)
	if symbolType == nil {
		t.Fatal("expected NpmPublisher_Validate to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected NpmPublisher_Validate function type to be printable")
	}
}

func TestAX7_NpmPublisher_Validate_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing NpmPublisher_Validate panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*NpmPublisher).Validate)
	if symbol.Pointer() == 0 {
		t.Fatal("expected NpmPublisher_Validate to have a callable entry point")
	}
}

func TestAX7_ReleaseExists_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ReleaseExists)
	if symbolType == nil {
		t.Fatal("expected ReleaseExists to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ReleaseExists function type to be printable")
	}
}

func TestAX7_ReleaseExists_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ReleaseExists panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ReleaseExists)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ReleaseExists to have a callable entry point")
	}
}

func TestAX7_ScoopPublisher_Name_Good(t *testing.T) {
	symbol := reflect.ValueOf((*ScoopPublisher).Name)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ScoopPublisher_Name to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ScoopPublisher_Name_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*ScoopPublisher).Name)
	if symbolType == nil {
		t.Fatal("expected ScoopPublisher_Name to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ScoopPublisher_Name function type to be printable")
	}
}

func TestAX7_ScoopPublisher_Name_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ScoopPublisher_Name panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*ScoopPublisher).Name)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ScoopPublisher_Name to have a callable entry point")
	}
}

func TestAX7_ScoopPublisher_Publish_Good(t *testing.T) {
	symbol := reflect.ValueOf((*ScoopPublisher).Publish)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ScoopPublisher_Publish to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ScoopPublisher_Publish_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*ScoopPublisher).Publish)
	if symbolType == nil {
		t.Fatal("expected ScoopPublisher_Publish to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ScoopPublisher_Publish function type to be printable")
	}
}

func TestAX7_ScoopPublisher_Publish_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ScoopPublisher_Publish panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*ScoopPublisher).Publish)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ScoopPublisher_Publish to have a callable entry point")
	}
}

func TestAX7_ScoopPublisher_Supports_Good(t *testing.T) {
	symbol := reflect.ValueOf((*ScoopPublisher).Supports)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ScoopPublisher_Supports to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ScoopPublisher_Supports_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*ScoopPublisher).Supports)
	if symbolType == nil {
		t.Fatal("expected ScoopPublisher_Supports to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ScoopPublisher_Supports function type to be printable")
	}
}

func TestAX7_ScoopPublisher_Supports_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ScoopPublisher_Supports panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*ScoopPublisher).Supports)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ScoopPublisher_Supports to have a callable entry point")
	}
}

func TestAX7_ScoopPublisher_Validate_Good(t *testing.T) {
	symbol := reflect.ValueOf((*ScoopPublisher).Validate)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ScoopPublisher_Validate to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ScoopPublisher_Validate_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*ScoopPublisher).Validate)
	if symbolType == nil {
		t.Fatal("expected ScoopPublisher_Validate to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ScoopPublisher_Validate function type to be printable")
	}
}

func TestAX7_ScoopPublisher_Validate_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ScoopPublisher_Validate panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*ScoopPublisher).Validate)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ScoopPublisher_Validate to have a callable entry point")
	}
}

func TestAX7_UploadArtifact_Good(t *testing.T) {
	symbol := reflect.ValueOf(UploadArtifact)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected UploadArtifact to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_UploadArtifact_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(UploadArtifact)
	if symbolType == nil {
		t.Fatal("expected UploadArtifact to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected UploadArtifact function type to be printable")
	}
}

func TestAX7_UploadArtifact_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing UploadArtifact panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(UploadArtifact)
	if symbol.Pointer() == 0 {
		t.Fatal("expected UploadArtifact to have a callable entry point")
	}
}
