// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package release

import (
	"reflect"
	"testing"
)

func TestAX7_CompareVersions_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(CompareVersions)
	if symbolType == nil {
		t.Fatal("expected CompareVersions to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected CompareVersions function type to be printable")
	}
}

func TestAX7_ConfigExists_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ConfigExists)
	if symbolType == nil {
		t.Fatal("expected ConfigExists to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ConfigExists function type to be printable")
	}
}

func TestAX7_ConfigExists_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ConfigExists panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ConfigExists)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ConfigExists to have a callable entry point")
	}
}

func TestAX7_ConfigPath_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ConfigPath)
	if symbolType == nil {
		t.Fatal("expected ConfigPath to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ConfigPath function type to be printable")
	}
}

func TestAX7_ConfigPath_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ConfigPath panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ConfigPath)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ConfigPath to have a callable entry point")
	}
}

func TestAX7_Config_ExpandEnv_Good(t *testing.T) {
	symbol := reflect.ValueOf((*Config).ExpandEnv)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Config_ExpandEnv to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Config_ExpandEnv_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*Config).ExpandEnv)
	if symbolType == nil {
		t.Fatal("expected Config_ExpandEnv to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Config_ExpandEnv function type to be printable")
	}
}

func TestAX7_Config_ExpandEnv_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Config_ExpandEnv panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*Config).ExpandEnv)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Config_ExpandEnv to have a callable entry point")
	}
}

func TestAX7_Config_GetProjectName_Good(t *testing.T) {
	symbol := reflect.ValueOf((*Config).GetProjectName)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Config_GetProjectName to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Config_GetProjectName_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*Config).GetProjectName)
	if symbolType == nil {
		t.Fatal("expected Config_GetProjectName to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Config_GetProjectName function type to be printable")
	}
}

func TestAX7_Config_GetProjectName_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Config_GetProjectName panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*Config).GetProjectName)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Config_GetProjectName to have a callable entry point")
	}
}

func TestAX7_Config_GetRepository_Good(t *testing.T) {
	symbol := reflect.ValueOf((*Config).GetRepository)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Config_GetRepository to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Config_GetRepository_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*Config).GetRepository)
	if symbolType == nil {
		t.Fatal("expected Config_GetRepository to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Config_GetRepository function type to be printable")
	}
}

func TestAX7_Config_GetRepository_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Config_GetRepository panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*Config).GetRepository)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Config_GetRepository to have a callable entry point")
	}
}

func TestAX7_Config_PublishersIter_Good(t *testing.T) {
	symbol := reflect.ValueOf((*Config).PublishersIter)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Config_PublishersIter to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Config_PublishersIter_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*Config).PublishersIter)
	if symbolType == nil {
		t.Fatal("expected Config_PublishersIter to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Config_PublishersIter function type to be printable")
	}
}

func TestAX7_Config_PublishersIter_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Config_PublishersIter panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*Config).PublishersIter)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Config_PublishersIter to have a callable entry point")
	}
}

func TestAX7_Config_SetOutput_Good(t *testing.T) {
	symbol := reflect.ValueOf((*Config).SetOutput)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Config_SetOutput to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Config_SetOutput_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*Config).SetOutput)
	if symbolType == nil {
		t.Fatal("expected Config_SetOutput to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Config_SetOutput function type to be printable")
	}
}

func TestAX7_Config_SetOutput_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Config_SetOutput panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*Config).SetOutput)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Config_SetOutput to have a callable entry point")
	}
}

func TestAX7_Config_SetOutputDir_Good(t *testing.T) {
	symbol := reflect.ValueOf((*Config).SetOutputDir)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Config_SetOutputDir to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Config_SetOutputDir_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*Config).SetOutputDir)
	if symbolType == nil {
		t.Fatal("expected Config_SetOutputDir to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Config_SetOutputDir function type to be printable")
	}
}

func TestAX7_Config_SetOutputDir_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Config_SetOutputDir panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*Config).SetOutputDir)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Config_SetOutputDir to have a callable entry point")
	}
}

func TestAX7_Config_SetOutputMedium_Good(t *testing.T) {
	symbol := reflect.ValueOf((*Config).SetOutputMedium)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Config_SetOutputMedium to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Config_SetOutputMedium_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*Config).SetOutputMedium)
	if symbolType == nil {
		t.Fatal("expected Config_SetOutputMedium to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Config_SetOutputMedium function type to be printable")
	}
}

func TestAX7_Config_SetOutputMedium_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Config_SetOutputMedium panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*Config).SetOutputMedium)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Config_SetOutputMedium to have a callable entry point")
	}
}

func TestAX7_Config_SetProjectDir_Good(t *testing.T) {
	symbol := reflect.ValueOf((*Config).SetProjectDir)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Config_SetProjectDir to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Config_SetProjectDir_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*Config).SetProjectDir)
	if symbolType == nil {
		t.Fatal("expected Config_SetProjectDir to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Config_SetProjectDir function type to be printable")
	}
}

func TestAX7_Config_SetProjectDir_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Config_SetProjectDir panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*Config).SetProjectDir)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Config_SetProjectDir to have a callable entry point")
	}
}

func TestAX7_Config_SetVersion_Good(t *testing.T) {
	symbol := reflect.ValueOf((*Config).SetVersion)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Config_SetVersion to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Config_SetVersion_Bad(t *testing.T) {
	symbolType := reflect.TypeOf((*Config).SetVersion)
	if symbolType == nil {
		t.Fatal("expected Config_SetVersion to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Config_SetVersion function type to be printable")
	}
}

func TestAX7_Config_SetVersion_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Config_SetVersion panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf((*Config).SetVersion)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Config_SetVersion to have a callable entry point")
	}
}

func TestAX7_DefaultConfig_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(DefaultConfig)
	if symbolType == nil {
		t.Fatal("expected DefaultConfig to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected DefaultConfig function type to be printable")
	}
}

func TestAX7_DefaultConfig_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DefaultConfig panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(DefaultConfig)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DefaultConfig to have a callable entry point")
	}
}

func TestAX7_DetermineVersion_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DetermineVersion panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(DetermineVersion)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DetermineVersion to have a callable entry point")
	}
}

func TestAX7_DetermineVersionWithContext_Good(t *testing.T) {
	symbol := reflect.ValueOf(DetermineVersionWithContext)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected DetermineVersionWithContext to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_DetermineVersionWithContext_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(DetermineVersionWithContext)
	if symbolType == nil {
		t.Fatal("expected DetermineVersionWithContext to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected DetermineVersionWithContext function type to be printable")
	}
}

func TestAX7_DetermineVersionWithContext_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DetermineVersionWithContext panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(DetermineVersionWithContext)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DetermineVersionWithContext to have a callable entry point")
	}
}

func TestAX7_Generate_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Generate panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Generate)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Generate to have a callable entry point")
	}
}

func TestAX7_GenerateWithConfig_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing GenerateWithConfig panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(GenerateWithConfig)
	if symbol.Pointer() == 0 {
		t.Fatal("expected GenerateWithConfig to have a callable entry point")
	}
}

func TestAX7_GenerateWithConfigWithContext_Good(t *testing.T) {
	symbol := reflect.ValueOf(GenerateWithConfigWithContext)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected GenerateWithConfigWithContext to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_GenerateWithConfigWithContext_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(GenerateWithConfigWithContext)
	if symbolType == nil {
		t.Fatal("expected GenerateWithConfigWithContext to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected GenerateWithConfigWithContext function type to be printable")
	}
}

func TestAX7_GenerateWithConfigWithContext_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing GenerateWithConfigWithContext panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(GenerateWithConfigWithContext)
	if symbol.Pointer() == 0 {
		t.Fatal("expected GenerateWithConfigWithContext to have a callable entry point")
	}
}

func TestAX7_GenerateWithContext_Good(t *testing.T) {
	symbol := reflect.ValueOf(GenerateWithContext)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected GenerateWithContext to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_GenerateWithContext_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(GenerateWithContext)
	if symbolType == nil {
		t.Fatal("expected GenerateWithContext to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected GenerateWithContext function type to be printable")
	}
}

func TestAX7_GenerateWithContext_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing GenerateWithContext panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(GenerateWithContext)
	if symbol.Pointer() == 0 {
		t.Fatal("expected GenerateWithContext to have a callable entry point")
	}
}

func TestAX7_IncrementMajor_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing IncrementMajor panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(IncrementMajor)
	if symbol.Pointer() == 0 {
		t.Fatal("expected IncrementMajor to have a callable entry point")
	}
}

func TestAX7_IncrementMinor_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing IncrementMinor panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(IncrementMinor)
	if symbol.Pointer() == 0 {
		t.Fatal("expected IncrementMinor to have a callable entry point")
	}
}

func TestAX7_IncrementVersion_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing IncrementVersion panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(IncrementVersion)
	if symbol.Pointer() == 0 {
		t.Fatal("expected IncrementVersion to have a callable entry point")
	}
}

func TestAX7_LoadConfig_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing LoadConfig panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(LoadConfig)
	if symbol.Pointer() == 0 {
		t.Fatal("expected LoadConfig to have a callable entry point")
	}
}

func TestAX7_LoadConfigAtPath_Good(t *testing.T) {
	symbol := reflect.ValueOf(LoadConfigAtPath)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected LoadConfigAtPath to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_LoadConfigAtPath_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(LoadConfigAtPath)
	if symbolType == nil {
		t.Fatal("expected LoadConfigAtPath to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected LoadConfigAtPath function type to be printable")
	}
}

func TestAX7_LoadConfigAtPath_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing LoadConfigAtPath panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(LoadConfigAtPath)
	if symbol.Pointer() == 0 {
		t.Fatal("expected LoadConfigAtPath to have a callable entry point")
	}
}

func TestAX7_LoadConfigWithMedium_Good(t *testing.T) {
	symbol := reflect.ValueOf(LoadConfigWithMedium)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected LoadConfigWithMedium to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_LoadConfigWithMedium_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(LoadConfigWithMedium)
	if symbolType == nil {
		t.Fatal("expected LoadConfigWithMedium to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected LoadConfigWithMedium function type to be printable")
	}
}

func TestAX7_LoadConfigWithMedium_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing LoadConfigWithMedium panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(LoadConfigWithMedium)
	if symbol.Pointer() == 0 {
		t.Fatal("expected LoadConfigWithMedium to have a callable entry point")
	}
}

func TestAX7_ParseCommitType_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ParseCommitType panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ParseCommitType)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ParseCommitType to have a callable entry point")
	}
}

func TestAX7_ParseVersion_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ParseVersion panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ParseVersion)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ParseVersion to have a callable entry point")
	}
}

func TestAX7_Publish_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Publish panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Publish)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Publish to have a callable entry point")
	}
}

func TestAX7_Run_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Run panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Run)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Run to have a callable entry point")
	}
}

func TestAX7_RunSDK_Good(t *testing.T) {
	symbol := reflect.ValueOf(RunSDK)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected RunSDK to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_RunSDK_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(RunSDK)
	if symbolType == nil {
		t.Fatal("expected RunSDK to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected RunSDK function type to be printable")
	}
}

func TestAX7_RunSDK_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing RunSDK panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(RunSDK)
	if symbol.Pointer() == 0 {
		t.Fatal("expected RunSDK to have a callable entry point")
	}
}

func TestAX7_ScaffoldConfig_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ScaffoldConfig)
	if symbolType == nil {
		t.Fatal("expected ScaffoldConfig to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ScaffoldConfig function type to be printable")
	}
}

func TestAX7_ScaffoldConfig_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ScaffoldConfig panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ScaffoldConfig)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ScaffoldConfig to have a callable entry point")
	}
}

func TestAX7_ValidateVersion_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ValidateVersion panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ValidateVersion)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ValidateVersion to have a callable entry point")
	}
}

func TestAX7_ValidateVersionIdentifier_Good(t *testing.T) {
	symbol := reflect.ValueOf(ValidateVersionIdentifier)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ValidateVersionIdentifier to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ValidateVersionIdentifier_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ValidateVersionIdentifier)
	if symbolType == nil {
		t.Fatal("expected ValidateVersionIdentifier to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ValidateVersionIdentifier function type to be printable")
	}
}

func TestAX7_ValidateVersionIdentifier_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ValidateVersionIdentifier panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ValidateVersionIdentifier)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ValidateVersionIdentifier to have a callable entry point")
	}
}

func TestAX7_WriteConfig_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing WriteConfig panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(WriteConfig)
	if symbol.Pointer() == 0 {
		t.Fatal("expected WriteConfig to have a callable entry point")
	}
}
