// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package ax

import (
	"reflect"
	"testing"
)

func TestAX7_Abs_Good(t *testing.T) {
	symbol := reflect.ValueOf(Abs)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Abs to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Abs_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Abs)
	if symbolType == nil {
		t.Fatal("expected Abs to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Abs function type to be printable")
	}
}

func TestAX7_Abs_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Abs panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Abs)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Abs to have a callable entry point")
	}
}

func TestAX7_Base_Good(t *testing.T) {
	symbol := reflect.ValueOf(Base)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Base to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Base_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Base)
	if symbolType == nil {
		t.Fatal("expected Base to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Base function type to be printable")
	}
}

func TestAX7_Base_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Base panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Base)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Base to have a callable entry point")
	}
}

func TestAX7_Chmod_Good(t *testing.T) {
	symbol := reflect.ValueOf(Chmod)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Chmod to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Chmod_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Chmod)
	if symbolType == nil {
		t.Fatal("expected Chmod to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Chmod function type to be printable")
	}
}

func TestAX7_Chmod_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Chmod panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Chmod)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Chmod to have a callable entry point")
	}
}

func TestAX7_Clean_Good(t *testing.T) {
	symbol := reflect.ValueOf(Clean)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Clean to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Clean_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Clean)
	if symbolType == nil {
		t.Fatal("expected Clean to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Clean function type to be printable")
	}
}

func TestAX7_Clean_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Clean panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Clean)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Clean to have a callable entry point")
	}
}

func TestAX7_CombinedOutput_Good(t *testing.T) {
	symbol := reflect.ValueOf(CombinedOutput)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected CombinedOutput to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_CombinedOutput_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(CombinedOutput)
	if symbolType == nil {
		t.Fatal("expected CombinedOutput to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected CombinedOutput function type to be printable")
	}
}

func TestAX7_CombinedOutput_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing CombinedOutput panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(CombinedOutput)
	if symbol.Pointer() == 0 {
		t.Fatal("expected CombinedOutput to have a callable entry point")
	}
}

func TestAX7_Create_Good(t *testing.T) {
	symbol := reflect.ValueOf(Create)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Create to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Create_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Create)
	if symbolType == nil {
		t.Fatal("expected Create to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Create function type to be printable")
	}
}

func TestAX7_Create_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Create panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Create)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Create to have a callable entry point")
	}
}

func TestAX7_DS_Good(t *testing.T) {
	symbol := reflect.ValueOf(DS)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected DS to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_DS_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(DS)
	if symbolType == nil {
		t.Fatal("expected DS to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected DS function type to be printable")
	}
}

func TestAX7_DS_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing DS panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(DS)
	if symbol.Pointer() == 0 {
		t.Fatal("expected DS to have a callable entry point")
	}
}

func TestAX7_Dir_Good(t *testing.T) {
	symbol := reflect.ValueOf(Dir)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Dir to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Dir_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Dir)
	if symbolType == nil {
		t.Fatal("expected Dir to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Dir function type to be printable")
	}
}

func TestAX7_Dir_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Dir panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Dir)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Dir to have a callable entry point")
	}
}

func TestAX7_Exec_Good(t *testing.T) {
	symbol := reflect.ValueOf(Exec)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Exec to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Exec_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Exec)
	if symbolType == nil {
		t.Fatal("expected Exec to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Exec function type to be printable")
	}
}

func TestAX7_Exec_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Exec panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Exec)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Exec to have a callable entry point")
	}
}

func TestAX7_ExecDir_Good(t *testing.T) {
	symbol := reflect.ValueOf(ExecDir)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ExecDir to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ExecDir_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ExecDir)
	if symbolType == nil {
		t.Fatal("expected ExecDir to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ExecDir function type to be printable")
	}
}

func TestAX7_ExecDir_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ExecDir panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ExecDir)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ExecDir to have a callable entry point")
	}
}

func TestAX7_ExecWithEnv_Good(t *testing.T) {
	symbol := reflect.ValueOf(ExecWithEnv)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ExecWithEnv to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ExecWithEnv_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ExecWithEnv)
	if symbolType == nil {
		t.Fatal("expected ExecWithEnv to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ExecWithEnv function type to be printable")
	}
}

func TestAX7_ExecWithEnv_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ExecWithEnv panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ExecWithEnv)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ExecWithEnv to have a callable entry point")
	}
}

func TestAX7_ExecWithWriters_Good(t *testing.T) {
	symbol := reflect.ValueOf(ExecWithWriters)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ExecWithWriters to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ExecWithWriters_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ExecWithWriters)
	if symbolType == nil {
		t.Fatal("expected ExecWithWriters to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ExecWithWriters function type to be printable")
	}
}

func TestAX7_ExecWithWriters_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ExecWithWriters panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ExecWithWriters)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ExecWithWriters to have a callable entry point")
	}
}

func TestAX7_Exists_Good(t *testing.T) {
	symbol := reflect.ValueOf(Exists)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Exists to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Exists_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Exists)
	if symbolType == nil {
		t.Fatal("expected Exists to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Exists function type to be printable")
	}
}

func TestAX7_Exists_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Exists panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Exists)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Exists to have a callable entry point")
	}
}

func TestAX7_Ext_Good(t *testing.T) {
	symbol := reflect.ValueOf(Ext)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Ext to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Ext_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Ext)
	if symbolType == nil {
		t.Fatal("expected Ext to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Ext function type to be printable")
	}
}

func TestAX7_Ext_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Ext panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Ext)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Ext to have a callable entry point")
	}
}

func TestAX7_FromSlash_Good(t *testing.T) {
	symbol := reflect.ValueOf(FromSlash)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected FromSlash to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_FromSlash_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(FromSlash)
	if symbolType == nil {
		t.Fatal("expected FromSlash to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected FromSlash function type to be printable")
	}
}

func TestAX7_FromSlash_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing FromSlash panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(FromSlash)
	if symbol.Pointer() == 0 {
		t.Fatal("expected FromSlash to have a callable entry point")
	}
}

func TestAX7_Geteuid_Good(t *testing.T) {
	symbol := reflect.ValueOf(Geteuid)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Geteuid to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Geteuid_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Geteuid)
	if symbolType == nil {
		t.Fatal("expected Geteuid to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Geteuid function type to be printable")
	}
}

func TestAX7_Geteuid_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Geteuid panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Geteuid)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Geteuid to have a callable entry point")
	}
}

func TestAX7_Getgid_Good(t *testing.T) {
	symbol := reflect.ValueOf(Getgid)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Getgid to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Getgid_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Getgid)
	if symbolType == nil {
		t.Fatal("expected Getgid to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Getgid function type to be printable")
	}
}

func TestAX7_Getgid_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Getgid panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Getgid)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Getgid to have a callable entry point")
	}
}

func TestAX7_Getuid_Good(t *testing.T) {
	symbol := reflect.ValueOf(Getuid)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Getuid to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Getuid_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Getuid)
	if symbolType == nil {
		t.Fatal("expected Getuid to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Getuid function type to be printable")
	}
}

func TestAX7_Getuid_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Getuid panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Getuid)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Getuid to have a callable entry point")
	}
}

func TestAX7_Getwd_Good(t *testing.T) {
	symbol := reflect.ValueOf(Getwd)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Getwd to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Getwd_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Getwd)
	if symbolType == nil {
		t.Fatal("expected Getwd to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Getwd function type to be printable")
	}
}

func TestAX7_Getwd_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Getwd panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Getwd)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Getwd to have a callable entry point")
	}
}

func TestAX7_IsAbs_Good(t *testing.T) {
	symbol := reflect.ValueOf(IsAbs)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected IsAbs to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_IsAbs_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(IsAbs)
	if symbolType == nil {
		t.Fatal("expected IsAbs to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected IsAbs function type to be printable")
	}
}

func TestAX7_IsAbs_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing IsAbs panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(IsAbs)
	if symbol.Pointer() == 0 {
		t.Fatal("expected IsAbs to have a callable entry point")
	}
}

func TestAX7_IsDir_Good(t *testing.T) {
	symbol := reflect.ValueOf(IsDir)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected IsDir to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_IsDir_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(IsDir)
	if symbolType == nil {
		t.Fatal("expected IsDir to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected IsDir function type to be printable")
	}
}

func TestAX7_IsDir_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing IsDir panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(IsDir)
	if symbol.Pointer() == 0 {
		t.Fatal("expected IsDir to have a callable entry point")
	}
}

func TestAX7_IsFile_Good(t *testing.T) {
	symbol := reflect.ValueOf(IsFile)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected IsFile to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_IsFile_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(IsFile)
	if symbolType == nil {
		t.Fatal("expected IsFile to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected IsFile function type to be printable")
	}
}

func TestAX7_IsFile_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing IsFile panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(IsFile)
	if symbol.Pointer() == 0 {
		t.Fatal("expected IsFile to have a callable entry point")
	}
}

func TestAX7_JSONMarshal_Good(t *testing.T) {
	symbol := reflect.ValueOf(JSONMarshal)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected JSONMarshal to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_JSONMarshal_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(JSONMarshal)
	if symbolType == nil {
		t.Fatal("expected JSONMarshal to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected JSONMarshal function type to be printable")
	}
}

func TestAX7_JSONMarshal_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing JSONMarshal panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(JSONMarshal)
	if symbol.Pointer() == 0 {
		t.Fatal("expected JSONMarshal to have a callable entry point")
	}
}

func TestAX7_JSONUnmarshal_Good(t *testing.T) {
	symbol := reflect.ValueOf(JSONUnmarshal)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected JSONUnmarshal to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_JSONUnmarshal_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(JSONUnmarshal)
	if symbolType == nil {
		t.Fatal("expected JSONUnmarshal to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected JSONUnmarshal function type to be printable")
	}
}

func TestAX7_JSONUnmarshal_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing JSONUnmarshal panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(JSONUnmarshal)
	if symbol.Pointer() == 0 {
		t.Fatal("expected JSONUnmarshal to have a callable entry point")
	}
}

func TestAX7_Join_Good(t *testing.T) {
	symbol := reflect.ValueOf(Join)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Join to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Join_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Join)
	if symbolType == nil {
		t.Fatal("expected Join to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Join function type to be printable")
	}
}

func TestAX7_Join_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Join panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Join)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Join to have a callable entry point")
	}
}

func TestAX7_LookPath_Good(t *testing.T) {
	symbol := reflect.ValueOf(LookPath)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected LookPath to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_LookPath_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(LookPath)
	if symbolType == nil {
		t.Fatal("expected LookPath to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected LookPath function type to be printable")
	}
}

func TestAX7_LookPath_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing LookPath panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(LookPath)
	if symbol.Pointer() == 0 {
		t.Fatal("expected LookPath to have a callable entry point")
	}
}

func TestAX7_Mkdir_Good(t *testing.T) {
	symbol := reflect.ValueOf(Mkdir)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Mkdir to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Mkdir_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Mkdir)
	if symbolType == nil {
		t.Fatal("expected Mkdir to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Mkdir function type to be printable")
	}
}

func TestAX7_Mkdir_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Mkdir panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Mkdir)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Mkdir to have a callable entry point")
	}
}

func TestAX7_MkdirAll_Good(t *testing.T) {
	symbol := reflect.ValueOf(MkdirAll)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected MkdirAll to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_MkdirAll_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(MkdirAll)
	if symbolType == nil {
		t.Fatal("expected MkdirAll to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected MkdirAll function type to be printable")
	}
}

func TestAX7_MkdirAll_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing MkdirAll panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(MkdirAll)
	if symbol.Pointer() == 0 {
		t.Fatal("expected MkdirAll to have a callable entry point")
	}
}

func TestAX7_MkdirTemp_Good(t *testing.T) {
	symbol := reflect.ValueOf(MkdirTemp)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected MkdirTemp to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_MkdirTemp_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(MkdirTemp)
	if symbolType == nil {
		t.Fatal("expected MkdirTemp to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected MkdirTemp function type to be printable")
	}
}

func TestAX7_MkdirTemp_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing MkdirTemp panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(MkdirTemp)
	if symbol.Pointer() == 0 {
		t.Fatal("expected MkdirTemp to have a callable entry point")
	}
}

func TestAX7_Open_Good(t *testing.T) {
	symbol := reflect.ValueOf(Open)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Open to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Open_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Open)
	if symbolType == nil {
		t.Fatal("expected Open to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Open function type to be printable")
	}
}

func TestAX7_Open_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Open panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Open)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Open to have a callable entry point")
	}
}

func TestAX7_ReadDir_Good(t *testing.T) {
	symbol := reflect.ValueOf(ReadDir)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ReadDir to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ReadDir_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ReadDir)
	if symbolType == nil {
		t.Fatal("expected ReadDir to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ReadDir function type to be printable")
	}
}

func TestAX7_ReadDir_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ReadDir panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ReadDir)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ReadDir to have a callable entry point")
	}
}

func TestAX7_ReadFile_Good(t *testing.T) {
	symbol := reflect.ValueOf(ReadFile)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ReadFile to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ReadFile_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ReadFile)
	if symbolType == nil {
		t.Fatal("expected ReadFile to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ReadFile function type to be printable")
	}
}

func TestAX7_ReadFile_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ReadFile panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ReadFile)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ReadFile to have a callable entry point")
	}
}

func TestAX7_Rel_Good(t *testing.T) {
	symbol := reflect.ValueOf(Rel)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Rel to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Rel_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Rel)
	if symbolType == nil {
		t.Fatal("expected Rel to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Rel function type to be printable")
	}
}

func TestAX7_Rel_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Rel panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Rel)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Rel to have a callable entry point")
	}
}

func TestAX7_RemoveAll_Good(t *testing.T) {
	symbol := reflect.ValueOf(RemoveAll)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected RemoveAll to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_RemoveAll_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(RemoveAll)
	if symbolType == nil {
		t.Fatal("expected RemoveAll to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected RemoveAll function type to be printable")
	}
}

func TestAX7_RemoveAll_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing RemoveAll panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(RemoveAll)
	if symbol.Pointer() == 0 {
		t.Fatal("expected RemoveAll to have a callable entry point")
	}
}

func TestAX7_ResolveCommand_Good(t *testing.T) {
	symbol := reflect.ValueOf(ResolveCommand)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected ResolveCommand to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_ResolveCommand_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(ResolveCommand)
	if symbolType == nil {
		t.Fatal("expected ResolveCommand to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected ResolveCommand function type to be printable")
	}
}

func TestAX7_ResolveCommand_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing ResolveCommand panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(ResolveCommand)
	if symbol.Pointer() == 0 {
		t.Fatal("expected ResolveCommand to have a callable entry point")
	}
}

func TestAX7_Run_Good(t *testing.T) {
	symbol := reflect.ValueOf(Run)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Run to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Run_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Run)
	if symbolType == nil {
		t.Fatal("expected Run to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Run function type to be printable")
	}
}

func TestAX7_Run_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Run panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Run)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Run to have a callable entry point")
	}
}

func TestAX7_RunDir_Good(t *testing.T) {
	symbol := reflect.ValueOf(RunDir)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected RunDir to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_RunDir_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(RunDir)
	if symbolType == nil {
		t.Fatal("expected RunDir to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected RunDir function type to be printable")
	}
}

func TestAX7_RunDir_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing RunDir panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(RunDir)
	if symbol.Pointer() == 0 {
		t.Fatal("expected RunDir to have a callable entry point")
	}
}

func TestAX7_Stat_Good(t *testing.T) {
	symbol := reflect.ValueOf(Stat)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected Stat to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_Stat_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(Stat)
	if symbolType == nil {
		t.Fatal("expected Stat to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected Stat function type to be printable")
	}
}

func TestAX7_Stat_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing Stat panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(Stat)
	if symbol.Pointer() == 0 {
		t.Fatal("expected Stat to have a callable entry point")
	}
}

func TestAX7_TempDir_Good(t *testing.T) {
	symbol := reflect.ValueOf(TempDir)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected TempDir to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_TempDir_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(TempDir)
	if symbolType == nil {
		t.Fatal("expected TempDir to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected TempDir function type to be printable")
	}
}

func TestAX7_TempDir_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing TempDir panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(TempDir)
	if symbol.Pointer() == 0 {
		t.Fatal("expected TempDir to have a callable entry point")
	}
}

func TestAX7_WriteFile_Good(t *testing.T) {
	symbol := reflect.ValueOf(WriteFile)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected WriteFile to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_WriteFile_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(WriteFile)
	if symbolType == nil {
		t.Fatal("expected WriteFile to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected WriteFile function type to be printable")
	}
}

func TestAX7_WriteFile_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing WriteFile panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(WriteFile)
	if symbol.Pointer() == 0 {
		t.Fatal("expected WriteFile to have a callable entry point")
	}
}

func TestAX7_WriteString_Good(t *testing.T) {
	symbol := reflect.ValueOf(WriteString)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected WriteString to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_WriteString_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(WriteString)
	if symbolType == nil {
		t.Fatal("expected WriteString to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected WriteString function type to be printable")
	}
}

func TestAX7_WriteString_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing WriteString panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(WriteString)
	if symbol.Pointer() == 0 {
		t.Fatal("expected WriteString to have a callable entry point")
	}
}
