// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package sdkcfg

import (
	"reflect"
	"testing"
)

func TestAX7_LoadProjectConfig_Good(t *testing.T) {
	symbol := reflect.ValueOf(LoadProjectConfig)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected LoadProjectConfig to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_LoadProjectConfig_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(LoadProjectConfig)
	if symbolType == nil {
		t.Fatal("expected LoadProjectConfig to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected LoadProjectConfig function type to be printable")
	}
}

func TestAX7_LoadProjectConfig_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing LoadProjectConfig panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(LoadProjectConfig)
	if symbol.Pointer() == 0 {
		t.Fatal("expected LoadProjectConfig to have a callable entry point")
	}
}
