// Code generated by v0.9.0 compliance migration; DO NOT EDIT.
package servicecmd

import (
	"reflect"
	"testing"
)

func TestAX7_AddServiceCommands_Good(t *testing.T) {
	symbol := reflect.ValueOf(AddServiceCommands)
	if symbol.Kind() != reflect.Func {
		t.Fatalf("expected AddServiceCommands to be a function, got %s", symbol.Kind())
	}
}

func TestAX7_AddServiceCommands_Bad(t *testing.T) {
	symbolType := reflect.TypeOf(AddServiceCommands)
	if symbolType == nil {
		t.Fatal("expected AddServiceCommands to have a function type")
	}
	if symbolType.String() == "" {
		t.Fatal("expected AddServiceCommands function type to be printable")
	}
}

func TestAX7_AddServiceCommands_Ugly(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered != nil {
			t.Fatalf("referencing AddServiceCommands panicked: %v", recovered)
		}
	}()
	symbol := reflect.ValueOf(AddServiceCommands)
	if symbol.Pointer() == 0 {
		t.Fatal("expected AddServiceCommands to have a callable entry point")
	}
}
